//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebManagementPortal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Choice()
        {
            this.RecLog = new RecordLog();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsCorrect { get; set; }
        public int AssessmentId { get; set; }
    
        public RecordLog RecLog { get; set; }
    
        public virtual Assessment Assessment { get; set; }
    }
}
