//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebManagementPortal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.Licenses = new HashSet<License>();
            this.RecLog = new RecordLog();
        }
    
        public int Id { get; set; }
        public string SchoolName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string PrimaryContractName { get; set; }
        public string PrimaryPhoneNumber { get; set; }
        public string PrimaryEmail { get; set; }
        public string SecondaryContractName { get; set; }
        public string SecondaryPhoneNumber { get; set; }
        public string SecondaryEmail { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public string TimeZone { get; set; }
    
        public RecordLog RecLog { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<License> Licenses { get; set; }
    }
}
