//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebManagementPortal.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MindSageDataModelsContainer : DbContext
    {
        public MindSageDataModelsContainer()
            : base("name=MindSageDataModelsContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CourseCatalog> CourseCatalogs { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<Lesson> Lessons { get; set; }
        public virtual DbSet<Advertisement> Advertisements { get; set; }
        public virtual DbSet<TopicOfTheDay> TopicOfTheDays { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<License> Licenses { get; set; }
        public virtual DbSet<TeacherKey> TeacherKeys { get; set; }
        public virtual DbSet<ImportContentConfiguration> ImportContentConfigurations { get; set; }
        public virtual DbSet<LessonItem> LessonItems { get; set; }
        public virtual DbSet<AssessmentItem> AssessmentItems { get; set; }
        public virtual DbSet<Assessment> Assessments { get; set; }
        public virtual DbSet<Choice> Choices { get; set; }
    }
}
