// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlow.GeneratedTests.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Add_New_Course_By_Student_CodeFeature : Xunit.IClassFixture<Add_New_Course_By_Student_CodeFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Add_New_Course_By_Student_Code.feature"
#line hidden
        
        public Add_New_Course_By_Student_CodeFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Add_New_Course_By_Student_Code", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
                    "f two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("Initialize mocking data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
 testRunner.And("System have UserProfile collection with JSON format are", @"[
{
""id"": ""teacher@mindsage.com"",
""Name"": ""Teacher"",
""ImageProfileUrl"": ""teacher.jpg"",
""Subscriptions"": [
{
	""Role"": ""Teacher"",
	""ClassRoomId"": ""ClassRoom01"",
	""ClassCalendarId"": ""ClassCalendar01"",
	""CreatedDate"": ""1/1/2016 00:00 am"",
	""ClassRoomName"": ""Emotional literacy"",
	""LicenseId"": ""License01""
}
]
},
{
""id"": ""sakul@mindsage.com"",
""Name"": ""Sakul"",
""ImageProfileUrl"": ""sakul.jpg"",
""Subscriptions"": []
},
]", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 34
 testRunner.And("System have ClassRoom collection with JSON format are", @"[
    {
        ""id"": ""ClassRoom01"",
        ""Name"": ""Emotional literacy"",
        ""CourseCatalogId"": ""CourseCatalog01"",
        ""CreatedDate"": ""2/1/2016"",
        ""Message"": ""Don't forget to comment a lesson!"",
        ""Lessons"":
        [
            {
                ""id"": ""Lesson01"",
                ""TotalLikes"": 0,
                ""LessonCatalogId"": ""LessonCatalog01""
            },
        ]
    }
]", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 54
 testRunner.And("System have LessonCatalog collection with JSON format are", @"[
    {
        ""id"": ""LessonCatalog01"",
        ""Title"": ""What Is Emotional Literacy?"",
        ""ShortTeacherLessonPlan"": ""short teacher lesson plan01"",
        ""FullTeacherLessonPlan"": ""full teacher lesson plan01"",
""PrimaryContentUrl"": ""PrimaryContent01"",
""ExtraContents"": [ 
{
	""id"": ""Extra01"",
	""ContentURL"": ""www.extracontent01.com"",
	""Description"": ""description01"",
	""IconURL"": ""extra01.jpg""
},
{
	""id"": ""Extra02"",
	""ContentURL"": ""www.extracontent02.com"",
	""Description"": ""description03"",
	""IconURL"": ""extra02.jpg""
},
{
	""id"": ""Extra03"",
	""ContentURL"": ""www.extracontent03.com"",
	""Description"": ""description03"",
	""IconURL"": ""extra03.jpg""
}
]
    },
]", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 86
    testRunner.And("System have ClassCalendar collection with JSON format are", @"[
    {
        ""id"": ""ClassCalendar01"",
        ""BeginDate"": ""2/1/2016"",
""ExpiredDate"": ""1/1/2017"",
        ""ClassRoomId"": ""ClassRoom01"",
        ""LessonCalendars"":
        [
            {
                ""Id"": ""LessonCalendar01"",
                ""LessonId"": ""Lesson01"",
                ""BeginDate"": ""2/1/2016"",
                ""LessonCatalogId"": ""LessonCatalog01""
            },
        ]
    },
]", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 106
 testRunner.And("System have UserActivity collection with JSON format are", "[\r\n]", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 111
 testRunner.And("System have StudentKey collection with JSON format are", "[\r\n\t{\r\n\t\t\"id\": \"StudentKey01\",\r\n\t\t\"Code\": \"StudentCode01\",\r\n\t\t\"Grade\": \"Grade01\"," +
                    "\r\n\t\t\"CourseCatalogId\": \"CourseCatalog01\",\r\n\t\t\"ClassRoomId\": \"ClassRoom01\",\r\n\t\t\"C" +
                    "reatedDate\": \"2/1/2016\",\r\n\t}\r\n]", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        public virtual void SetFixture(Add_New_Course_By_Student_CodeFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Add_New_Course_By_Student_Code")]
        [Xunit.TraitAttribute("Description", "User add new course by using the right code Then system add new course to the use" +
            "r\'s subscription")]
        [Xunit.TraitAttribute("Category", "mock")]
        public virtual void UserAddNewCourseByUsingTheRightCodeThenSystemAddNewCourseToTheUserSSubscription()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User add new course by using the right code Then system add new course to the use" +
                    "r\'s subscription", new string[] {
                        "mock"});
#line 126
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 127
    testRunner.Given("Today is \'2/8/2016 00:00 am\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 128
    testRunner.When("UserProfile \'sakul@mindsage.com\' Add new course by using code \'StudentCode01\' and" +
                    " grade \'Grade01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 129
    testRunner.Then("System upsert user id \'sakul@mindsage.com\' UserProfile\'s subscriptions collection" +
                    " with JSON format are", @"[
{
""Role"": ""Student"",
""ClassRoomId"": ""ClassRoom01"",
""ClassCalendarId"": ""ClassCalendar01"",
""CreatedDate"": ""2/8/2016 00:00 am"",
""ClassRoomName"": ""Emotional literacy"",
""LicenseId"": ""License01"",
""CourseCatalogId"": ""CourseCatalog01"",
""LastActiveDate"": ""2/8/2016 00:00 am"",
}
]", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 144
 testRunner.And("System upsert user id \'sakul@mindsage.com\' UserActivity\'s LessonActivities collec" +
                    "tion with JSON format are", "[\r\n{\r\n\"LessonId\": \"Lesson01\",\r\n\"TotalContentsAmount\": 4,\r\n\"SawContentIds\": [],\r\n\"" +
                    "CreatedCommentAmount\": 0,\r\n\"ParticipationAmount\": 0,\r\n\"BeginDate\": \"2/1/2016\",\r\n" +
                    "}\r\n]", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Add_New_Course_By_Student_Code")]
        [Xunit.TraitAttribute("Description", "User add new course by using the incorrect code Then system don\'t add new course " +
            "to the user\'s subscription")]
        [Xunit.TraitAttribute("Category", "mock")]
        public virtual void UserAddNewCourseByUsingTheIncorrectCodeThenSystemDonTAddNewCourseToTheUserSSubscription()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User add new course by using the incorrect code Then system don\'t add new course " +
                    "to the user\'s subscription", new string[] {
                        "mock"});
#line 159
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 160
    testRunner.Given("Today is \'2/8/2016 00:00 am\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 161
    testRunner.When("UserProfile \'sakul@mindsage.com\' Add new course by using code \'IncorrectCode\' and" +
                    " grade \'Grade01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 162
    testRunner.Then("System doesn\'t add new subscription", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 163
 testRunner.And("System doesn\'t add UserActivity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Add_New_Course_By_Student_Code")]
        [Xunit.TraitAttribute("Description", "User add new course by using the right code but incorrect grade Then system don\'t" +
            " add new course to the user\'s subscription")]
        [Xunit.TraitAttribute("Category", "mock")]
        public virtual void UserAddNewCourseByUsingTheRightCodeButIncorrectGradeThenSystemDonTAddNewCourseToTheUserSSubscription()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User add new course by using the right code but incorrect grade Then system don\'t" +
                    " add new course to the user\'s subscription", new string[] {
                        "mock"});
#line 166
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 167
    testRunner.Given("Today is \'2/8/2016 00:00 am\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 168
    testRunner.When("UserProfile \'sakul@mindsage.com\' Add new course by using code \'StudentCode01\' and" +
                    " grade \'IncorrectGrade\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 169
    testRunner.Then("System doesn\'t add new subscription", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 170
 testRunner.And("System doesn\'t add UserActivity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Add_New_Course_By_Student_Code")]
        [Xunit.TraitAttribute("Description", "User add new course by using code and grade are incorrect Then system don\'t add n" +
            "ew course to the user\'s subscription")]
        [Xunit.TraitAttribute("Category", "mock")]
        public virtual void UserAddNewCourseByUsingCodeAndGradeAreIncorrectThenSystemDonTAddNewCourseToTheUserSSubscription()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User add new course by using code and grade are incorrect Then system don\'t add n" +
                    "ew course to the user\'s subscription", new string[] {
                        "mock"});
#line 173
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 174
    testRunner.Given("Today is \'2/8/2016 00:00 am\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 175
    testRunner.When("UserProfile \'sakul@mindsage.com\' Add new course by using code \'IncorrectCode\' and" +
                    " grade \'IncorrectGrade\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 176
    testRunner.Then("System doesn\'t add new subscription", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 177
 testRunner.And("System doesn\'t add UserActivity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Add_New_Course_By_Student_Code")]
        [Xunit.TraitAttribute("Description", "User add new course by using the right code but the class doesn\'t have a teacher " +
            "account Then system doesn\'t add new course to the user\'s subscription")]
        [Xunit.TraitAttribute("Category", "mock")]
        public virtual void UserAddNewCourseByUsingTheRightCodeButTheClassDoesnTHaveATeacherAccountThenSystemDoesnTAddNewCourseToTheUserSSubscription()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User add new course by using the right code but the class doesn\'t have a teacher " +
                    "account Then system doesn\'t add new course to the user\'s subscription", new string[] {
                        "mock"});
#line 180
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 181
    testRunner.Given("Today is \'2/8/2016 00:00 am\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 182
 testRunner.And("System have UserProfile collection with JSON format are", "[\r\n{\r\n\"id\": \"sakul@mindsage.com\",\r\n\"Name\": \"Sakul\",\r\n\"ImageProfileUrl\": \"sakul.jp" +
                    "g\",\r\n\"Subscriptions\": []\r\n},\r\n]", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 193
    testRunner.When("UserProfile \'sakul@mindsage.com\' Add new course by using code \'StudentCode01\' and" +
                    " grade \'Grade01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 194
 testRunner.Then("System doesn\'t add new subscription", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 195
 testRunner.And("System doesn\'t add UserActivity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Add_New_Course_By_Student_Code")]
        [Xunit.TraitAttribute("Description", "User add new course by using the right code but the ClassRoom doesn\'t existing Th" +
            "en system doesn\'t add new course to the user\'s subscription")]
        [Xunit.TraitAttribute("Category", "mock")]
        public virtual void UserAddNewCourseByUsingTheRightCodeButTheClassRoomDoesnTExistingThenSystemDoesnTAddNewCourseToTheUserSSubscription()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User add new course by using the right code but the ClassRoom doesn\'t existing Th" +
                    "en system doesn\'t add new course to the user\'s subscription", new string[] {
                        "mock"});
#line 198
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 199
    testRunner.Given("Today is \'2/8/2016 00:00 am\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 200
 testRunner.And("System have ClassRoom collection with JSON format are", "[]", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 204
    testRunner.When("UserProfile \'sakul@mindsage.com\' Add new course by using code \'StudentCode01\' and" +
                    " grade \'Grade01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 205
 testRunner.Then("System doesn\'t add new subscription", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 206
 testRunner.And("System doesn\'t add UserActivity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Add_New_Course_By_Student_Code")]
        [Xunit.TraitAttribute("Description", "User add new course by using the right code but the ClassCalendar doesn\'t existin" +
            "g Then system doesn\'t add new course to the user\'s subscription")]
        [Xunit.TraitAttribute("Category", "mock")]
        public virtual void UserAddNewCourseByUsingTheRightCodeButTheClassCalendarDoesnTExistingThenSystemDoesnTAddNewCourseToTheUserSSubscription()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User add new course by using the right code but the ClassCalendar doesn\'t existin" +
                    "g Then system doesn\'t add new course to the user\'s subscription", new string[] {
                        "mock"});
#line 209
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 210
    testRunner.Given("Today is \'2/8/2016 00:00 am\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 211
 testRunner.And("System have ClassCalendar collection with JSON format are", "[]", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 215
    testRunner.When("UserProfile \'sakul@mindsage.com\' Add new course by using code \'StudentCode01\' and" +
                    " grade \'Grade01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 216
 testRunner.Then("System doesn\'t add new subscription", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 217
 testRunner.And("System doesn\'t add UserActivity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Add_New_Course_By_Student_Code")]
        [Xunit.TraitAttribute("Description", "Incorrect user add new course by using the right informations Then system doesn\'t" +
            " add new course to the user")]
        [Xunit.TraitAttribute("Category", "mock")]
        public virtual void IncorrectUserAddNewCourseByUsingTheRightInformationsThenSystemDoesnTAddNewCourseToTheUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Incorrect user add new course by using the right informations Then system doesn\'t" +
                    " add new course to the user", new string[] {
                        "mock"});
#line 220
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 221
    testRunner.Given("Today is \'2/8/2016 00:00 am\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 222
 testRunner.And("System have UserProfile collection with JSON format are", @"[
{
""id"": ""teacher@mindsage.com"",
""Name"": ""Teacher"",
""ImageProfileUrl"": ""teacher.jpg"",
""Subscriptions"": [
{
	""Role"": ""Teacher"",
	""ClassRoomId"": ""ClassRoom01"",
	""ClassCalendarId"": ""ClassCalendar01"",
	""CreatedDate"": ""1/1/2016 00:00 am"",
	""ClassRoomName"": ""Emotional literacy"",
	""LicenseId"": ""License01""
}
]
}
]", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 242
    testRunner.When("UserProfile \'sakul@mindsage.com\' Add new course by using code \'StudentCode01\' and" +
                    " grade \'Grade01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 243
 testRunner.Then("System doesn\'t add new subscription", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 244
 testRunner.And("System doesn\'t add UserActivity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Add_New_Course_By_Student_Code")]
        [Xunit.TraitAttribute("Description", "User who already have course want to add the same course Then system doesn\'t add " +
            "new course to the user")]
        [Xunit.TraitAttribute("Category", "mock")]
        public virtual void UserWhoAlreadyHaveCourseWantToAddTheSameCourseThenSystemDoesnTAddNewCourseToTheUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User who already have course want to add the same course Then system doesn\'t add " +
                    "new course to the user", new string[] {
                        "mock"});
#line 247
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 248
    testRunner.Given("Today is \'2/8/2016 00:00 am\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 249
 testRunner.And("System have UserProfile collection with JSON format are", @"[
{
""id"": ""teacher@mindsage.com"",
""Name"": ""Teacher"",
""ImageProfileUrl"": ""teacher.jpg"",
""Subscriptions"": [
{
	""Role"": ""Teacher"",
	""ClassRoomId"": ""ClassRoom01"",
	""ClassCalendarId"": ""ClassCalendar01"",
	""CreatedDate"": ""1/1/2016 00:00 am"",
	""ClassRoomName"": ""Emotional literacy"",
	""LicenseId"": ""License01""
}
]
},
{
""id"": ""sakul@mindsage.com"",
""Name"": ""Sakul"",
""ImageProfileUrl"": ""sakul.jpg"",
""Subscriptions"": [
{
	""Role"": ""Student"",
	""ClassRoomId"": ""ClassRoom01"",
	""ClassCalendarId"": ""ClassCalendar01"",
	""CreatedDate"": ""1/1/2016 00:00 am"",
	""ClassRoomName"": ""Emotional literacy"",
	""LicenseId"": ""License01""
}
]
},
]", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 284
    testRunner.When("UserProfile \'sakul@mindsage.com\' Add new course by using code \'StudentCode01\' and" +
                    " grade \'Grade01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 285
 testRunner.Then("System doesn\'t add new subscription", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 286
 testRunner.And("System doesn\'t add UserActivity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Add_New_Course_By_Student_Code")]
        [Xunit.TraitAttribute("Description", "User add new course by using deleted student code Then system doesn\'t add new cou" +
            "rse to the user\'s subscription")]
        [Xunit.TraitAttribute("Category", "mock")]
        public virtual void UserAddNewCourseByUsingDeletedStudentCodeThenSystemDoesnTAddNewCourseToTheUserSSubscription()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User add new course by using deleted student code Then system doesn\'t add new cou" +
                    "rse to the user\'s subscription", new string[] {
                        "mock"});
#line 290
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 291
    testRunner.Given("Today is \'2/8/2016 00:00 am\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 292
 testRunner.And("System have StudentKey collection with JSON format are", "[\r\n\t{\r\n\t\t\"id\": \"StudentKey01\",\r\n\t\t\"Code\": \"StudentCode01\",\r\n\t\t\"Grade\": \"Grade01\"," +
                    "\r\n\t\t\"CourseCatalogId\": \"CourseCatalog01\",\r\n\t\t\"ClassRoomId\": \"ClassRoom01\",\r\n\t\t\"C" +
                    "reatedDate\": \"2/1/2016\",\r\n\t\t\"DeletedDate\": \"2/1/2016\",\r\n\t}\r\n]", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 306
    testRunner.When("UserProfile \'sakul@mindsage.com\' Add new course by using code \'StudentCode01\' and" +
                    " grade \'Grade01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 307
 testRunner.Then("System doesn\'t add new subscription", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 308
 testRunner.And("System doesn\'t add UserActivity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                Add_New_Course_By_Student_CodeFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                Add_New_Course_By_Student_CodeFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
